#!/bin/bash

file=$1

if [[ "$file" = "" ]] ; then
    echo "Usage:  $0 <file with smatch messages>"
    exit 1
fi

outfile="kernel.gfp_flags"
bin_dir=$(dirname $0)
remove=$(echo ${bin_dir}/../smatch_data/${outfile}.remove)
tmp=$(mktemp /tmp/smatch.XXXX)

echo "// list of GFP flag parameters." > $outfile
echo '// generated by `gen_gfp_flags.sh`' >> $outfile
${bin_dir}/trace_params.pl $file \
    kmalloc 1                    \
    kzalloc 1                    \
    kcalloc 2                    \
    | sort -u > $tmp
cat $tmp $remove $remove 2> /dev/null | sort | uniq -u >> $outfile
rm $tmp
echo "Done.  List saved as '$outfile'"
